blank_issues_enabled: false
contact_links:
  - name: Implement a new feature / improvement
    url: https://feedback.js.wiki/wiki
    about: Submit ideas for new features or improvements.
  - name: Errors / Bugs
    url: https://github.com/Requarks/wiki/discussions/categories/error-bug-report
    about: Create a discussion around the bug / error.
